### PR TITLE
Fixes for Volume Profile

### LINKED ISSUE #318: Volume Profile price ranges are uneven
According to referenced descriptions, Volume Profile should:
```
  1. Find the high-low range for closing prices for the entire period.  
  2. Divide this range by 12 to create 12 equal price zones.
```
Instead, vp does:
```
vp_ranges = array_split(vp, width)
```
This does not divide the price into equal ranges. It divides the set of candles into ranges that each contain an equal number of candles. Even if the candles are sorted by price (close), the distribution is uneven, based on whatever range of prices happen to appear in the bar subset. 

**Expected behavior**

The price width of each range should be the same. 

Pandas TA is awesome. Thank you!

### LINKED ISSUE #319: Volume Profile positive and negative volumes are signed to volume, not price
According to referenced descriptions, Volume Profile should:
```
  4. Divide the volume into positive volume and negative volume (optional). 

Note that negative volume for a price zone is the sum of volume for all down days in that zone, 
while positive volume is the total of volume for all up days in that price zone.
```

Instead, vp does:
```
    signed_volume = signed_series(volume, initial=1)
    pos_volume = signed_volume[signed_volume > 0] * volume
    neg_volume = signed_volume[signed_volume < 0] * -volume
```

This creates a time series that is signed according to whether the volume increased or decreased on that candle. 

**Expected behavior**

The sign should be determined by the change in price. 

We want to see how much volume accompanied rising prices, or falling prices - not how much volume accompanied rising volume and falling volume.

### PR DESCRIPTION
**Pull request by delicateear**
Divide bins evenly by price if sort_close. Fixes #318 

Positive and negative volume based on price direction, not volume direction. Fixes #319 

Minor refactoring for clarity.

### CODE REVIEW

**Review by twopirllc — COMMENTED** [review]
It all looks good and the fixes are welcome 😄.

I only suggest not changing lines 23-27 since some may pass in a different source for whatever reason.

**Comment by delicateear** [comment]
Aha, thanks for the observation; I did not realize what was going on with the Series names. Fixed. 

I also updated the docstring. User jeichenseerNRX is also me - I need to sort out my SSH keys. = /

**Comment by twopirllc** [comment]
@delicateear,

> Aha, thanks for the observation; I did not realize what was going on with the Series names. Fixed.
> I also updated the docstring. User jeichenseerNRX is also me - I need to sort out my SSH keys. = /

No worries. Thanks for improving **vp** promptly. 😎  I will roll  it into the _development_ branch soon and let you know when it's ready to check out before I push it to _main_.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @delicateear,

I pushed it to the _development_ branch if you want to check it out before it's pushed to _main_.
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks for the contribution. 😎 

KJ

**Comment by delicateear** [comment]
Looks good to me. 👍🏾
jhno

**Comment by twopirllc** [comment]
@delicateear,

Thank you Sir.

KJ

**Pull request merged**
