### PR TITLE
add pivots

### PR DESCRIPTION
**Pull request by hamedf62**
according to issues added Pivot indicator

### CODE REVIEW

**Comment by twopirllc** [comment]
Hello @hamedf62,

Thanks for making a PR for the **pivots**. I will edit and merge it as soon as I can.

Kind Regards,
KJ

**Comment by SergioQuinonez** [comment]
@hamedf62 I'm getting the next error with pandas `1.5.0`

```
  File "/Users/sq/project/.env/lib/python3.10/site-packages/pandas_ta/overlap/pivot.py", line 27, in pivots
    to_datetime(close.index, errors='coerce', unit="ms")
  File "/Users/sq/project/.env/lib/python3.10/site-packages/pandas/core/generic.py", line 1526, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

I know that pandas-ta use pandas `1.2.0`, but the main project is using `1.5.0` 😞 , the curios thing is that all the other indicators used works perfectly with `1.5.0`.

**Comment by twopirllc** [comment]
Hello @SergioQuinonez

The minimum Pandas for Pandas TA is 1.2. I am sure when I can finally get around to merging and testing it, it will be fine with Pandas 1.5. If you or @hamedf62 have a fix for this _ValueError_ you encountered please feel free to make a PR 😎 .

Kind Regards
KJ

**Comment by SergioQuinonez** [comment]
> Hello @SergioQuinonez
> 
> The minimum Pandas for Pandas TA is 1.2. I am sure when I can finally get around to merging and testing it, it will be fine with Pandas 1.5. If you or @hamedf62 have a fix for this _ValueError_ you encountered please feel free to make a PR 😎 .
> 
> Kind Regards KJ

Thanks for reply! I would love to contribute with the solution, unfortunately I don't have much experience with pandas :(

**Comment by twopirllc** [comment]
Hello @hamedf62 & @SergioQuinonez,

Just updated the _development_ branch with _overlap_ **pivots**. Please give them a go when you get a chance. Thanks for your submission and patience.

Kind Regards,
KJ

**Pull request merged**
