### PR TITLE
Fixing ALMA calculation per Issue 455

### PR DESCRIPTION
**Pull request by jaggas**
https://github.com/twopirllc/pandas-ta/issues/455

### CODE REVIEW

**Comment by twopirllc** [comment]
Hello @jaggas,

Curious if you seen Issue #373. I revamped it then but it is on the _development_ branch if you want to give it a spin.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Let me know what you think. If you want to add another version, we can do that also.

Kind Regards,
KJ

**Comment by jaggas** [comment]
Wow, I looked over the issues and completely missed that one somehow. I'll check it out and get back with you tommorrow.

Thanks,
Jeff

**Comment by jaggas** [comment]
Ok, so just compared your implementation with mine. I attached a csv with output from both versions. Delta between the values is negligable (<0.01%). So I'd say to take your changes addressing #373. Your code is very efficient - nicely done. I'll have to check out whatever tricks you played with numpy.
[alma_comparison.csv](https://github.com/twopirllc/pandas-ta/files/7742384/alma_comparison.csv)

**Comment by twopirllc** [comment]
Hi @jaggas,

Thank you! Not gonna lie, it took some time to figure out. Wish all of them could be that fast and compact.

I do appreciate that you took the initiative to code a solution instead of letting it sit in the Issue pile. If **alma** wasn't too difficult, perhaps you might want to try your hand at a few other _Good First Issue_ indicators that I haven't been able to work on yet. 😎  If it's a new Indicator, I recommend following Creating a Custom Indicator: The Big 4 #355.

Kind Regards,
KJ

**Comment by jaggas** [comment]
Sure thing, I'll take a look at those and pick one to work on.

Thanks,
Jeff

**Pull request closed without merging**
