### PR TITLE
ha efficiency update

### PR DESCRIPTION
**Pull request by BCusack**
ha.py is slow on large datasets 3000+ rows
Iterating the dataframe in a for loop is slow
HA_open and HA_close to list and iterate the list 
between 40x to 60x efficiency improvement

image

### CODE REVIEW

**Comment by twopirllc** [comment]
Hello @BCusack,

> ha.py is slow on large datasets 3000+ rows

Yes.

> Iterating the dataframe in a for loop is slow

Yes. I knew there was a quicker implementation.

> HA_open and HA_close to list and iterate the list
between 40x to 60x efficiency improvement

Awesome! Thanks for contributing! 😎 

Kind Regards,
KJ

**Comment by twopirllc** [comment]
@BCusack,

Would you mind checking out the _development_ branch and updating HA and making a new PR? If not I will make the changes and update _development_.

Thanks
KJ

**Comment by BCusack** [comment]
Sure thing - later today 👍

**Comment by twopirllc** [comment]
@BCusack,

Anytime this week. Trying to knock out some low conflict code where possible. 😎

**Comment by BCusack** [comment]
Hi @twopirllc 
 
I just checked on the dev branch for ha and found  - [https://github.com/twopirllc/pandas-ta/pull/592](https://github.com/twopirllc/pandas-ta/pull/592 )
This depends on the Numba lib which is compatable with python 3.10 or later and may not be future proof (I occassionally use 3.11).
The pull request I propose uses zero lib dependancies and on a quick test is still faster than the 592 pull solution.

_Low spec test machine_
With simple list: 0.03125s
With numpy/numba: 2.484375s

I can complete timeit tests later this week - just a bit swampt ATM.

Would you like me to still pull to dev?

Regards 
BCusack

**Comment by twopirllc** [comment]
@BCusack

>Low spec test machine
With simple list: 0.03125s
With numpy/numba: 2.484375s

Nice!

> Would you like me to still pull to dev?

The merge will give you contribution. Up to you. 😎 

KJ

**Comment by BCusack** [comment]
@twopirllc 
Can be closed - moved to dev - https://github.com/twopirllc/pandas-ta/pull/662

**Pull request closed without merging**
