### PR TITLE
Add signal line to TSI

### PR DESCRIPTION
**Pull request by danlim-wz**
Hi KJ,

Thanks for allowing me to contribute to this awesome project! This PR adds the signal line to the TSI as discussed in issue #351.

I have also adjusted the SMI slightly to account for the change.

I have tested and verified the changes manually as well as via your momentum testing script:
Screenshot from 2021-07-25 18-23-00
Screenshot from 2021-07-25 18-07-47

I used a default signal value of `13` which is in line with that of TradingView.

Regards,
Daniel

### CODE REVIEW

**Comment by twopirllc** [comment]
Hi @danlim-wz,

This looks great and you thankfully covered the additional required pieces for inclusion... including testing! Thank you! 😎 

> I have also adjusted the SMI slightly to account for the change.

Excellent!

> Thanks for allowing me to contribute to this awesome project! 

No worries! Thank you! I appreciate the contributions that help us all! I will merge it in as soon as I can and let you know when it is available for testing on the _development_ branch.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @danlim-wz,

I pushed it to the _development_ branch if you want to check it out before it's pushed to _main_.
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks for the contribution. 😎 

KJ

**Comment by ramarajusk1308** [comment]
Thanks for your efforts and contribution towards trading community. God Bless !!

**Comment by twopirllc** [comment]
@ramarajusk1308,

Thanks! Would appreciate a coffee as support. 😎 

["Buy Me A Coffee"](https://www.buymeacoffee.com/twopirllc)

**Pull request merged**
