### PR TITLE
Update fisher.py

### PR DESCRIPTION
**Pull request by moritzgun**
position[i] is raising a keyError

### CODE REVIEW

**Comment by twopirllc** [comment]
Hello @moritzgun,

Could you please provide breaking code that is causing these errors so we are both on the same page and getting the same errors?

Kind Regards,
KJ

**Comment by moritzgun** [comment]
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html

that's the correct way of accessing elements of pandas dfs.

I get a KeyError when running df.ta.fisher() saying that position does not have the key '0'. Changing to iloc for accessing df elements solves that issue for me. Im running python 3.7 on Windows btw.

Kind regards,

Moritz

**Comment by twopirllc** [comment]
@moritzgun,

> https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html
>  that's the correct way of accessing elements of pandas dfs.

I appreciate the contributions! 😎 

> I get a KeyError when running df.ta.fisher() saying that position does not have the key '0'. Changing to iloc for accessing df elements solves that issue for me. Im running python 3.7 on Windows btw.

Gotcha. It still does not hurt to have some reproducible code for future reference and testing purposes.

Currently I am adding and testing some new features and plan to address these PRs as soon as I can.

Thanks,
KJ

**Comment by moritzgun** [comment]
@twopirllc Alright! Thanks mate, appreciate your fast reply!

**Comment by twopirllc** [comment]
@moritzgun,

Thanks for your patience and contributions. All the PRs are now up on the _development_ branch. It would be great if you could test them out before I push them to the _main_ branch.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks,
KJ

**Pull request merged**
