### PR TITLE
Signals module

### PR DESCRIPTION
**Pull request by lluissalord**
Hi @twopirllc 

For my own projects I would like to have some indicators which mark when events (or interesting period) are happening. As it could be for example the overbought or oversold based on RSI or crossovers between `ema(length=50)` and `ema(length=200)`. I believe that the best think can be to integrate this type of indicators on your library.

Here I present just a quick example because before starting to code more of them I would like to discuss the following points:

- Should we split between puntual events (as it could be a crossover) and interesting periods (as it could be oversold periods)?
- Which could be the best name for the subpackage?
- Which kind of name do we want for this indicators? (for example mark 'XA'/'XB' for crossing above/below and 'A'/'B' for periods above/below)

Please add more points to discuss if you believe so.

Regards,
Lluis

### CODE REVIEW

**Comment by twopirllc** [comment]
Hey @lluissalord,

Once again thank you for your contributions and commitment to help improve the library for everyone.

An events like system could be useful, to what extent, I am unsure right now.  I guess a subpackage name could be events or signals I suppose.  I have made a ```cross``` indicator under utils.py.

I'll pull what you have into the under the development branch and see what you have in mind and we can go from there.

Regards,
KJ

**Comment by twopirllc** [comment]
Hey @lluissalord,

Out of curiosity, I am wondering if these signals should be added to the indicator itself as a additional return... like how Ichimoku returns two DataFrames.  For example, ```macd``` returning the original ```macd``` DataFrame and another if kwargs['signals'] is set as well.  Otherwise the signal/event directory will contain signals for nearly every indicator.

Thoughts?

Thanks,
KJ

**Comment by lluissalord** [comment]
Hi,

This was something I though could be interesting too, and probably then it will create cleaner package. 

However, I am wondering how would then someone who is only interested on the signals get them without all the other information. Probably well naming these signals or creating somehow a list of which columns are signals would solve that.

Any other idea?

Regards,
Lluís

**Comment by lluissalord** [comment]
The idea of having the signals within the indicator code is a good idea, and the code you showed seems a pretty good start. However, we have to make sure that we cover all the desired cases. I would think that the cases to take into account are:
- [x] Cross of indicator above/below a/some constant value
- [ ] Cross of current indicator above/below another indicator
- [ ] Get signals without knowing which are the _best_ values to generate the signals
- [ ] A way of returning default signals to be used with methods like `ta(kind='all')` and do not mix arguments between indicators (probably highly related to previous case)

I believe that if we find a general structure to allow all the indicators have this flexibility, then we would have a very good package.

Thoughts or more cases to take into account?

Regards,
Lluís

**Comment by lluissalord** [comment]
I tried to improve a bit your example. It have some trade off that if you set that you want signals, then you will have all of them (maybe in the cases where does not apply to an indicator to have all of them the default could be `None` instead of the number or the serie.

```python
from pandas import DataFrame
from ..overlap.ema import ema
from ..utils import above_value, below_value, get_offset, verify_series, cross

def rma(close, length=None, offset=None, **kwargs):
    """Indicator: wildeR's Moving Average (RMA)"""
    # Validate Arguments
    close = verify_series(close)
    length = int(length) if length and length > 0 else 10
    min_periods = int(kwargs['min_periods']) if 'min_periods' in kwargs and kwargs['min_periods'] is not None else length
    offset = get_offset(offset)
    alpha = (1.0 / length) if length > 0 else 0.5

    # Calculate Result
    rma = close.ewm(alpha=alpha, min_periods=min_periods).mean()

    # Offset
    if offset != 0:
        rma = rma.shift(offset)

    # Name & Category
    rma.name = f"RMA_{length}"
    rma.category = 'overlap'

    signals = kwargs.pop('signals', False)
    if signals:
        xa = kwargs.pop('xa', 289)
        xb = kwargs.pop('xb', 295)
        xserie = kwargs.pop('xserie', ema(close=close, length=200))
        signalsdf = DataFrame({rma.name: rma})
        if xa is not None and isinstance(xa, (int, float)):
            crossed_above = above_value(rma, xa, offset=offset)
            signalsdf[crossed_above.name] = crossed_above
        if xb is not None and isinstance(xb, (int, float)):
            crossed_below = below_value(rma, xb, offset=offset)
            signalsdf[crossed_below.name] = crossed_below
        if xserie is not None and verify_series(xserie):
            cross_serie_above = cross(rma, xserie, above=True, asint=True)
            cross_serie_below = cross(rma, xserie, above=False, asint=True)
            signalsdf[cross_serie_above.name] = cross_serie_above
            signalsdf[cross_serie_below.name] = cross_serie_below

        return signalsdf
    else:
        return rma
```

What do you think?

Regards,
Lluís

**Comment by lluissalord** [comment]
Hi @twopirllc,

I have updated the comment with a more complet version.

Let me know your thoughts.

Regards,
Lluís

**Comment by twopirllc** [comment]
Hey @lluissalord,

Hope you had a good weekend. Sorry I did not respond this weekend, was trying to make some headway on another package.

Anyhow, last question first.  When ```kwargs.pop('signal_indicators', False)``` will that affect to other indicators which are also called with ```ta(kind='all', **kwargs)```?  Nope, ```kwargs['signal_indicators']``` is handled by the function receiving it and is not removed during the processing of ```ta(kind='all', **kwargs)```.

Your implementation looks pretty solid.  Some will be case by case but that should be manageable for the time being.  I have a few more commits to make to ```development``` before I merge it in.  See if you can create a test case as well.  It need not apply for all indicators.

Thanks,
KJ

**Pull request merged**
