### PR TITLE
Added nadaraya-watson channel indicator

### LINKED ISSUE #697: Add the Nadaraya-Watson Channels indicator
**Is your feature request related to a problem? Please describe.**
The Nadaraya-Watson indicator is in essence  the calculation of the Nadaraya-Watson regression, by iterating over the input data, computing the distances between data points, and applying the specified kernel to compute the weights. The predicted response variable is then computed based on these weights. Finally, the predicted response variable is returned as a DataFrame with the column name 'kernel'.

It raised some eye-browns when it was published by LuxAlgo in tradingview, with many youtube videos showing impressive results, albeit with some caveats, such as repainting. 

**Describe the solution you'd like**
An indicator to be created, with upper and lower channels

**Inspirational source**
https://www.tradingview.com/script/Iko0E2kL-Nadaraya-Watson-Envelope-LuxAlgo/

### PR DESCRIPTION
**Pull request by tdgrossi**
Closes #697 

Hi! This code will add the nadaraya-watson channel indicator. It was inspired by [this](https://www.tradingview.com/script/Iko0E2kL-Nadaraya-Watson-Envelope-LuxAlgo/), and [this](https://medium.com/@yashaswa/backtesting-the-viral-nadaraya-watson-envelop-trading-indicator-in-python-b800a70e8167), but turned out quite different in how it approaches the calculation. My implementation is more of a "pure" nadaraya-watson regression, and quite frankly, more efficient with less nested loops. In addition, it allows users to use different kernel models to calculate the regressions (Lux's uses the gaussian kernel).
I'm not a mathematician so don't ask me difficult questions.

### CODE REVIEW

**Comment by twopirllc** [comment]
Hello @tdgrossi,

Cool! 😎 Would be great if you could checkout the _development_ branch and make a PR for that branch. If not possible, I will do it when I get a chance.

Kind Regards,
KJ

**Comment by tdgrossi** [comment]
Sure thing!

**Comment by pybymo** [comment]
Hi, to use this indicator, should I do file changes manually? because my pandas-ta is up to date and there isn't nwc!

**Comment by tdgrossi** [comment]
Hi @pybymo , we haven't merged this indicator to the master branch, so it's not part of pandas. Further, mind you that I found out that the indicator as is contains lookahead bias (aka repaints). I do have a working version without repainting, but never got a chance to put it here. Might someday.

**Pull request closed without merging**
