### PR TITLE
Add GHA workflow for testing

### PR DESCRIPTION
**Pull request by Karsten-Fyhn**
This PR adds a Github Actions workflow for testing the pandas-ta package, by running its test suite.

Currently, there are tests that are failing in the main branch. These are not visible in this PR, as the workflow is not being run (I assume because I am not a maintainer of this repo). To see the output, go to my fork of the project: https://github.com/Karsten-Fyhn/pandas-ta/pull/1/checks

### CODE REVIEW

**Comment by twopirllc** [comment]
@Karsten-Fyhn,

Is this one better than PR #581 ?

KJ

**Comment by Karsten-Fyhn** [comment]
It's the same one - but now actually ready for review :)

**Comment by twopirllc** [comment]
Hi @Karsten-Fyhn,

Looks good mostly. 😎 

It seems to be testing the _main_ branch which is good. But can it also test the _development_ branch?

Thanks,
KJ

**Comment by Karsten-Fyhn** [comment]
> Hi @Karsten-Fyhn,
> 
> Looks good mostly. sunglasses
> 
> It seems to be testing the _main_ branch which is good. But can it also test the _development_ branch?
> 
> Thanks, KJ

Hi @twopirllc ,
Sure - just added it.
Best,
Karsten

**Comment by twopirllc** [comment]
Hmmm... still installing ```pandas-ta-0.3.14b0``` and a test failing.

KJ

**Comment by Karsten-Fyhn** [comment]
> Hmmm... still installing `pandas-ta-0.3.14b0` and a test failing.
> 
> KJ

Aah - I understand what you mean now. I have set it up for running on pull requests TO the development branch now. But since this is a PR to master, then it does not run against that branch. If you would like to see it run against the development branch, we would have to open a new PR with my branch against the development branch.

Maybe it is because I am not familiar with your development flow, so I am not constructing this optimally - how do you normally move from idea, to development, to master?

**Comment by twopirllc** [comment]
@Karsten-Fyhn,

No worries.

> how do you normally move from idea, to development, to master?

Starting with _v0.3.14b_, I decided to do all the major work via the _development_ branch and periodically update the _main_ branch. At the current pace, it's going to be awhile before I can update the _main_ branch since I have at least 6 more TA Lib indicators to port and various other bugs to resolve.

I either make a new branch off _development_ or just edit _development_ and run tests on that branch before updating Github's _development_ branch. So having the GHA testing the _development_ branch also would be reassuring. 😄 

Maybe this [GH Action from branch other than main](https://stackoverflow.com/questions/63480433/how-to-run-a-github-action-from-a-branch-other-than-master) may help. 🤷🏼‍♂️ 

I appreciate you taking the time to help. 😎 

Thanks
KJ

**Pull request closed without merging**
