### PR TITLE
Adding Chandelier Exit Indicator

### PR DESCRIPTION
**Pull request by amey-P**
Adding the Chandelier Exit indicator under `overlap` category. The logic for calculation is picked from #559

### CODE REVIEW

**Comment by twopirllc** [comment]
Hi @amey-P,

Excellent! I'll merge it as soon as I can. Thanks for contributing! 😎 

Kind Regards
KJ

**Comment by swapniel99** [comment]
Hi is there an update on when this will be released?

**Comment by twopirllc** [comment]
Hello @swapniel99,

Thank you for reaching out regarding the release of Chandelier Exit indicator. We appreciate your interest and enthusiasm.

At this time, we understand that limited free time is a challenge for many individuals. We apologize for any inconvenience caused by the delay in providing you with an update.

Our team is working diligently to ensure the timely release of our products. However, due to unforeseen circumstances, we are experiencing some delays in the development and testing process. We are committed to delivering a high-quality and reliable offering, and we want to make sure that all aspects are thoroughly evaluated before its release.

While we do not have a specific release date to share with you at the moment, we assure you that we are making every effort to expedite the process without compromising on the quality. We understand the value of your time and we apologize for any frustration this may have caused.

Once again, we appreciate your patience and understanding. If you have any further questions or concerns, please feel free to reach out. We are here to assist you.

Kind regards,
KJ

**Comment by twopirllc** [comment]
Hello @amey-P & @swapniel99,

Just added **chandelier_exit** to the _development_ branch. Refactored it and added some additional parameters; see ```help(ta.chandelier_exit)```.

Please check that the values are returning as expected. ✅
If not, please make a new PR with fixes if possible or at least help identify lines that need editing to do so.

Thanks @amey-P  for the submission as well as your patience!
KJ

**Pull request merged**
