### PR TITLE
Jurik JMA indicator

### PR DESCRIPTION
**Pull request by mihakralj**
Jurik indicator - JMA

### CODE REVIEW

**Comment by twopirllc** [comment]
Hello @mihakralj,

Cool! 😎 Thanks for contributing! I will merge it in as soon as I can and let you know when it's testable on the _development_ branch.

Kind Regards,
KJ

**Comment by mihakralj** [comment]
My pleasure! 😊
Please wait for an updatebof this PR, I found an embarrassing bug in a math of Volty calculation...

**Comment by twopirllc** [comment]
Hello @mihakralj,

I pushed it to the _development_ branch if you want to check it out before it's pushed to _main_.
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks for the contribution. 😎 

KJ

**Comment by mihakralj** [comment]
modifications changed the math and the updated jma is no longer as smooth as the submitted code. I can chase what broke, but let me show you the graphics from the control data. On the screenshots below, blue is the input, yellow is my (original) jma, white is  what I called from pandas_ta:
image
image
image
image

**Comment by mihakralj** [comment]
Here is the code that I used above; the control file (JMA-test.csv) is available on my github [here](https://github.com/mihakralj/jurik_jma_python)
```
import pandas as pd
import pandas_ta as ta
import numpy as np
import plotly.graph_objects as go

dfin = pd.read_csv (r"JMA-test.csv")
df=pd.DataFrame()
tests=['Spike', 'Impulse', 'Triangle', 'Sawtooth', 'Sine', 'Chirp', 'White', 'Gauss', 'B', 'HF', 'Impulse+HF', 'Sawtooth+HF', 'Sine+G', 'Chirp+G', 'Market', 'Complex']
for test in tests:
    df['input']=dfin[test]
    df['control']=dfin[test+'-JMA']
    df['ta_jma']=ta.jma(df['input'], length=10, phase=0)
    df['jma']=jma(df['input'], length=10, phase=0)

    fig = go.Figure(data=go.Scatter(y=df['input'], name='input'))
    #fig.add_scatter(y=df['control'], name='control', marker_color='yellow')
    fig.add_scatter(y=df['ta_jma'], name='ta_jma', marker_color='white')
    fig.add_scatter(y=df['jma'], name='jma', marker_color='yellow')
    fig.update_layout(xaxis_rangeslider_visible=False, margin=dict(l=0, r=10, t=0, b=0), showlegend=False, title={'text':test, 'y':0.9})
    fig.layout.template = 'plotly_dark'
    fig.show() 
```

**Comment by mihakralj** [comment]
I think I found it; 
line 37 ( `beta = 0.45 * (length - 1) / (0.45 * (length - 1) + 2.0) `) should be:
`beta = 0.45 * (_length - 1) / (0.45 * (_length - 1) + 2.0) `

After this change, the control and the submitted code create identical result.

**Comment by twopirllc** [comment]
@mihakralj,

Thanks for checking the code promptly and finding the error! I apologize for the resultant mistake upon the variable renaming and will update it asap.

Thanks,
KJ

**Comment by twopirllc** [comment]
@mihakralj,

Ok. It's the _development_ branch is updated. Give it another shot please.

Thanks,
KJ

**Comment by mihakralj** [comment]
Checked. All ok! 👍

**Comment by twopirllc** [comment]
@mihakralj 

Awesome! Thank you!
KJ

**Pull request merged**
