### PR TITLE
bugfix RSI, use ema, not rma, see doc

### PR DESCRIPTION
**Pull request by floatinghotpot**
align code with doc

### CODE REVIEW

**Comment by twopirllc** [comment]
Hello @floatinghotpot,

Thanks for pointing out the error in the documentation. However it is not an indicator implementation error. I test indicators against TA Lib if there are common indicators in Pandas TA. In this care, TA Lib's **RSI** uses **RMA** for it's calculations and not **EMA**. I apologize for the confusion but appreciate the contribution.

Kind Regards,
KJ

**Comment by floatinghotpot** [comment]
rsi

Thanks for the quick response. 
Here is an example (reference line: 20/80). The first one is using EMA, the second one is using RMA implementation in pandas-ta.
It seems that the RMA will seldom trigger a buying signal.

**Comment by floatinghotpot** [comment]
rsi

Thanks for the quick response. 
Here is an example (reference line: 20/80). The first one is using EMA, the second one is using RMA implementation in pandas-ta.
It seems that the RMA will seldom trigger a buying signal.

**Comment by floatinghotpot** [comment]
I checked the following article:
https://www.tradingview.com/support/solutions/43000502338-relative-strength-index-rsi/
It did use RMA instead of EMA, and also mentioned using reference line: 30/70. 
The article also mentioned 20/80 reference line, but in above example, with RMA, 20/80 reference line is not useful at all. 

rsi2
It seems fine, the result of RMA with 30/70 is quite similar result with EMA and 20/80 reference line.

So, using RMA with 30/70 is okay. Thanks for explanation.

**Comment by twopirllc** [comment]
Hi @floatinghotpot,

I appreciate the contributions.

Are you refering to the 20/80 lines in the code with ```signal_indicators``` condition? If so, that was a submission by another user that wanted it. I make no judgement on that. Users are empowered to make their own trading signals from the indicators.

For the purpose of Pandas TA, I am only concerned about at least matching what TA Lib returns. If there is no TA Lib version, then I try TradingView since it is the next most popular and likely used platform with many public indicators. Sadly though, there are no standards regarding TA indicators since different platforms use different variations likely due to language of choice 🤷🏼‍♂️ .  For instance from the TA Lib source of ```ta_EMA.c``` the following comment regarding it's calculation:

```c
   /* The first EMA is calculated differently. It
    * then become the seed for subsequent EMA.
    *
    * The algorithm for this seed vary widely.
    * Only 3 are implemented here:
    *
    * TA_MA_CLASSIC:
    *    Use a simple MA of the first 'period'.
    *    This is the approach most widely documented.
    *
    * TA_MA_METASTOCK:
    *    Use first price bar value as a seed
    *    from the begining of all the available
    *    data.
    *
    * TA_MA_TRADESTATION:
    *    Use 4th price bar as a seed, except when
    *    period is 1 who use 2th price bar or something
    *    like that... (not an obvious one...).
    */
```

Hope this makes some sense and feel free to contribute to make this a better library for us all. 😎 

Thanks,
KJ

**Pull request closed without merging**
