### PR TITLE
Adding CTI indicator

### PR DESCRIPTION
**Pull request by whubsch**
I pulled together this Correlation Trend Indicator which I found in the Stocks & Commodities magazine from early last year but was unable to find anywhere other than Trading View. It's an oscillator that tries to indicate how similar a price trend is to a straight line.

### CODE REVIEW

**Comment by twopirllc** [comment]
Hello @whubsch,

Awesome! I will merge it into development as soon as I can. I appreciate the contribution. 😎 

Kind Regards,
KJ

**Review by twopirllc — APPROVED** [review]

**Comment by twopirllc** [comment]
Hello @whubsch,

So it appears that **cti** is equivalent to **linreg**'s ```r=True``` option and perfectly correlated.

Screen Shot 2021-04-12 at 8 07 40 AM

So we can add **cti** or make it a wrapper around **linreg**'s ```r=True```. What do you think?

Thanks,
KJ

**Comment by whubsch** [comment]
Nice catch, I didn't see that option in **linreg** when I was looking for a possible alternative. I would vote for keeping **cti**, but turning it into a wrapper for **linreg** as you suggest. However, I would also suggest the **linreg** function adopt numpy's sliding_window_view, which makes the function 30-40x faster. Let me know what you think.

**Comment by twopirllc** [comment]
@whubsch,

Thanks for the swift response.

Yeah, I was reading the code and realized it looked very similar to the general _linear regression_ calculation. We can keep **cti** as a wrapper.

> However, I would also suggest the linreg function adopt numpy's sliding_window_view, which makes the function 30-40x faster.

I noticed that also and the speed boost it provided! 😎  Nice find! I didn't know **numpy** had that function. If you find any other indicators that can use a boost, which is probably most, please let me know.

Thanks again for the contribution!

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @whubsch,

Thanks for contributing! It's been merged into development version. If you would like to test it out before it gets pushed to main, you can install the development version:

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

I hope to push it to main no later than this weekend.

Thanks,
KJ

**Comment by whubsch** [comment]
Looks good and runs as expected for me. Thanks KJ.

**Pull request closed without merging**
