### PR TITLE
Update vwap.py

### PR DESCRIPTION
**Pull request by YuvalWein**
An Attempt to fix the VWAP problem presented in this issue:
https://github.com/twopirllc/pandas-ta/issues/38

Is it fixing the problem?

### CODE REVIEW

**Comment by twopirllc** [comment]
Hi @YuvalWein,

I don't know _yet_ if there is a problem. I recommended that **casterock** check out Issue #74 to see if that resolves his confusion or question. Maybe the indicator should include the post processing code in **vwap** as boolean argument. Namely:

```python
# Set the index to mean_close and in ascending order
vp['mean_close'] = round(vp['mean_close'], 2)
vp.set_index('mean_close', inplace=True)
vp.sort_index(ascending=True, inplace=True)
print("Sorted by mean_close\n", vp, "\n") # Visual Table Check
```

**Comment by YuvalWein** [comment]
Hi KJ,

> I don't know _yet_ if there is a problem. I recommended that **casterock** check out Issue #74 to see if that resolves his confusion or question. Maybe the indicator should include the post processing code in **vwap** as boolean argument. Namely:
> 
> ```python
> # Set the index to mean_close and in ascending order
> vp['mean_close'] = round(vp['mean_close'], 2)
> vp.set_index('mean_close', inplace=True)
> vp.sort_index(ascending=True, inplace=True)
> print("Sorted by mean_close\n", vp, "\n") # Visual Table Check
> ```
> 
> Thoughts?

Im a little bit confused,
I thought that the problem with the VWAP is that it doesn't calculate the value per day.
That means that the VWAP is not calculated as intra-day indicator (as shown in [investopedia](https://www.investopedia.com/terms/v/vwap.asp)) ,
but as a multi-day indicator.

What I mean is that in the current code the cumsum is done from the first cell of the data frame,
to the final cell. 
But the "classic" VWAP calculation is done by cumsum every day separately (as @codesutras mentioned in issue #38).

About the snippet of code and #74 that you have added, I didn't quite understood the connection to #38.

> Also, thanks for your assistance in providing answers and PRs. I appreciate it.

Well, you are doing a great job with pandas_ta, its a wonderful tool,
and Im happy to help when I got the time :)

**Comment by twopirllc** [comment]
Hi @YuvalWein,

That did the trick! Excellent work!

I am adding an ```anchor``` parameter that defaults to "D". So depending on the index values, it will implement various [Pandas Timeseries Offset Aliases](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-offset-aliases). I should have it on the _development_ branch soon.

I appreciate your help in making this library better.

Thank you!
KJ

**Comment by YuvalWein** [comment]
> Hi @YuvalWein,
> 
> That did the trick! Excellent work!
> 
> I am adding an `anchor` parameter that defaults to "D". So depending on the index values, it will implement various [Pandas Timeseries Offset Aliases](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-offset-aliases). I should have it on the _development_ branch soon.

Great!!

> I appreciate your help in making this library better.

My pleasure, happy to help

**Pull request merged**
