### PR TITLE
added 'equal' parameter to cross & cross_value functions

### PR DESCRIPTION
**Pull request by TheWCKD**
Before pull request: 
```python
s1 = pd.Series([-2, -1, 0, 1, 2])
ta.cross_value(s1, 0, above=True, asint=False)

# False even though it crosses 0 to the positive side
0    False
1    False
2    False
3    False
4    False
Name: None_XB_0, dtype: bool
```
```python
s1 = pd.Series([2, 1, 0, -1, -2])
ta.cross_value(s1, 0, above=False, asint=False)

# False even though it crosses 0 to the negative side
0    False
1    False
2    False
3    False
4    False
Name: None_XB_0, dtype: bool

```

After pull request:
```python
s1 = pd.Series([-2, -1, 0, 1, 2])
ta.cross_value(s1, 0, equal=True, above=True, asint=False)

# Notice not it is True when it crosses to the positive side while being equal to the value
0    False
1    False
2    True
3    False
4    False
Name: None_XB_0, dtype: bool
```
```python
s1 = pd.Series([2, 1, 0, -1, -2])
ta.cross_value(s1, 0, equal=True, above=False, asint=False)

# Notice not it is True when it crosses to the negative side while being equal to the value
0    False
1    False
2    True
3    False
4    False
Name: None_XB_0, dtype: bool
```

### CODE REVIEW

**Comment by twopirllc** [comment]
Hello @TheWCKD,

Nice. I like you made it optional as well. Though if you don't mind, could you resubmit using the _development_ branch instead of _main_?

Thanks,
KJ

**Comment by TheWCKD** [comment]
Sure thing, @twopirllc, will do tomorrow! Thanks!

**Comment by twopirllc** [comment]
@TheWCKD,

No worries. Do you have any solutions or good ideas regarding Issues #500 and #560 since you are familiar with ```cross_value```?

Thanks

**Comment by TheWCKD** [comment]
@twopirllc Will definitely take a look over them on Monday and see if I can fix them!

**Comment by twopirllc** [comment]
Hi @TheWCKD

The changes are on the _development_ branch if you want to check them out. Let me know if it works as intended.

Thanks,
KJ

**Pull request closed without merging**
