### PR TITLE
Update pandas to 2.0

### PR DESCRIPTION
**Pull request by khiemdoan**

### CODE REVIEW

**Comment by twopirllc** [comment]
Hi @khiemdoan,

It is uncertain how many others are still on at least Pandas 1.2.0 or higher. Not sure if forcing 2.0 is recommended at this time. However users are more than welcome to use any version greater than 1.2.0 and it shouldn't (theoretically) impact them if they do so.

KJ

**Comment by krema** [comment]
There are a few breaking changes in the 2.0 version, which may cause certain indicators to break. One example is the mcgd indicator, which relies on the now-removed Series.append() method.

You can find more information about these changes in the official Pandas documentation here: [removal-of-prior-version-deprecations-changes](https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html#removal-of-prior-version-deprecations-changes)

**Comment by khiemdoan** [comment]
I have tested `mcgd `  indicator of `pandas_ta` with `pandas 2.0` already. It ran without any error or warning.
image

**Comment by baotang2118** [comment]
FYI: `pandas 2.0` is good, however, some of indicator have issue with NA value, I thought it is the problem with `pyarrow`. Here is the workaround if you are using engine `pyarrow`, otherwise, it is good to upgrade to `pandas 2.0`.

https://stackoverflow.com/questions/75264528/boolean-value-of-na-is-too-ambiguous

**Pull request merged**
