### PR TITLE
RMA: use SMA for seeding the series

### PR DESCRIPTION
**Pull request by mihakralj**
Related to Issue #402

### CODE REVIEW

**Comment by twopirllc** [comment]
@mihakralj,

If we can numpy it as much as possible, that would be awesome! 😎 

KJ

**Comment by mihakralj** [comment]
I literally replicated the SMA-generating code from EMA indicator - and I'd suggest we don't tinker any differently with RMA, compared to EMA.

RMA is the same as EMA, just the alpha factor is not 2/(n+1) and is 1/n instead. That is the only difference between RMA and EMA. Code should (ideally) reflect that.

**Comment by mihakralj** [comment]
If you'd want to refactor it properly, I'd suggest we open-up EMA indicator enough to allow different alpha factors as optional parameters/kwargs - and then create RMA that is just calling EMA with specific alpha factor. Ideally, code for RMA should not exist but should call EMA(alpha=1/n) instead

**Comment by twopirllc** [comment]
@mihakralj,

Yeah I noticed, no issue. I have too many current things lingering in my mind 🤣  that a context switch can be costly, so I appreciate the help. 😎 

Thanks,
KJ

**Comment by twopirllc** [comment]
@mihakralj 

> If you'd want to refactor it properly, I'd suggest we open-up EMA indicator enough to allow different alpha factors as optional parameters/kwargs - and then create RMA that is just calling EMA with specific alpha factor. Ideally, code for RMA should not exist but should call EMA(alpha=1/n) instead

Please make a separate PR so I can see the changes and test their impact. There are a lot of changes from the current PyPi version (0.3.14b) and the _development_ branch.

Thanks,
KJ

**Comment by mihakralj** [comment]
[(this is kettle calling the pot black...)](https://github.com/mihakralj/QuantLib/tree/main/QuantLib/MovingAvg) I am doing exactly the same mistake in my C# real-time indicator library.

I don't have to recalculate the whole output series when a new data is added to an input; I calculate and append only the last value of the indicator as I keep the history within the Class. Also, I can update the last value of the input and the last value of the output is updated with no need for a full recalculation. And I use events to communicate between indicators.

**Comment by mihakralj** [comment]
Refactoring of EMA in Python will have to wait - my free time is preoccupied with completing C# QuantLib TA library...

**Comment by twopirllc** [comment]
> [(this is kettle calling the pot black...)](https://github.com/mihakralj/QuantLib/tree/main/QuantLib/MovingAvg) I am doing exactly the same mistake in my C# real-time indicator library.
> 
> I don't have to recalculate the whole output series when a new data is added to an input; I calculate and append only the last value of the indicator as I keep the history within the Class. Also, I can update the last value of the input and the last value of the output is updated with no need for a full recalculation. And I use events to communicate between indicators.

Yeah I have been trying to learn from the ground up Incremental Calculations, but academic and basic information/material is hard to find. I understand the big picture, just not enough exposure to the details. If you have any good resources/material, that would be great!

KJ

**Comment by mihakralj** [comment]
I am literally reverse-engineering the historical algos (including yours) and converting them from sequencing to recursive. Then I run validation tests against TA-LIB, Skender.Stock.Indicators and (soon) Pandas-TA, where I generate a random list, recursively calculate values using my algo and then compare outputs. If results differ, unit tests fail. 

Recursive algos are available for some indicators (for example, EMA is recursive), but not for others (SMA requires a sliding buffer of size [length] to implement it recursively.

If you have time and interest, grab Quantlib .NET interactive notebooks in /Docs folder (they require installed dotnet framework and VS.Code with .NET Interactive extension installed) and play with QuantLib samples. Your library is a huge north star:https://github.com/mihakralj/QuantLib/blob/main/Docs/coverage.md

**Comment by twopirllc** [comment]
@mihakralj

> I am literally reverse-engineering the historical algos (including yours) and converting them from sequencing to recursive. Then I run validation tests against TA-LIB, Skender.Stock.Indicators and (soon) Pandas-TA, where I generate a random list, recursively calculate values using my algo and then compare outputs. If results differ, unit tests fail.

Nice.

> Recursive algos are available for some indicators (for example, EMA is recursive), but not for others (SMA requires a sliding buffer of size [length] to implement it recursively.

Gotcha. 

> If you have time and interest, grab Quantlib .NET interactive notebooks in /Docs folder (they require installed dotnet framework and VS.Code with .NET Interactive extension installed) and play with QuantLib samples. Your library is a huge north star:https://github.com/mihakralj/QuantLib/blob/main/Docs/coverage.md

Thank you! Thanks for sharing; good stuff and looks clean. Do you have any good resources on incremental calculations that helped you? I thought about C# years ago when I was checking out MultiCharts. Hopefully I can make time to check it out... as you know there is a **lot** to do. 🤣 I am trying to knock out as much of this [TODO](https://github.com/twopirllc/pandas-ta/tree/development#todo) as quickly as possible this year.

KJ

**Comment by mihakralj** [comment]
Ah no, that is a different QuantLib... 😊 My C# library named QuantLib is a young kiddo, mere few months old!

**Comment by twopirllc** [comment]
@mihakralj,

I'm aware. But the name reminded me of the original C++ one. All good though.

**Comment by twopirllc** [comment]
@mihakralj,

Please let me know if the new _development_ branch version works as intended. It's passed my basic _tests/_ so I'm complacent for now.

Thanks,
KJ

**Pull request merged**
