### PR TITLE
Zigzag indicator implemented from issue #443

### PR DESCRIPTION
**Pull request by aligheshlaghi97**
Hi again @twopirllc
I removed my previous fork, but I understood that I was not right doing that, cause I added the code to main branch anyway and then send PR to development branch. Or maybe I am wrong again. If so please let me know and make any modifications you want.
Thank you

### CODE REVIEW

**Comment by twopirllc** [comment]
@aligheshlaghi97,

Seems ok. I will take it from here.

Thanks for contributing. 😎 
KJ

**Comment by aligheshlaghi97** [comment]
@twopirllc  
That's an honor for me to contribute in this great project, and resolve issue #443 .
If there was any problems with my implementation, please let me know, so I can correct it.

**Comment by twopirllc** [comment]
Hi @aligheshlaghi97,

Thanks for including an additional indicator to the library. In the future, please make one PR per indicator/bug et al. Independent/atomic PRs helps minimize any any additional edits before the merge into the existing library. 😎 

Also other than the detailed comments for __alphatrend__ in in PR #694, is code the same between these two PRs?

Thanks

**Comment by aligheshlaghi97** [comment]
Hello @twopirllc 

Thanks for your time and attention, and I totally understand the problem you declare and I think I could make a new branch in my local containing the information from main branch of pandas-ta. Then I could have sent every implementation in a unique way. Actually I can do it right now to remove my requests and send them again, or you can separate the two indicators (ZigZag and AlphaTrend) from two different git commits I made.
But on the other hand, if possible, please merge the PRs as my team (and maybe some people who created or contributed in the issue) need these two indicators. And the good point about that is can make more PR as my previous PR is closed and done working with, so I can send request to the target branch easily.

**Comment by twopirllc** [comment]
@aligheshlaghi97

> Actually I can do it right now to remove my requests and send them again, or you can separate the two indicators (ZigZag and AlphaTrend) from two different git commits I made.

> And to answer your question, the second PR in https://github.com/twopirllc/pandas-ta/pull/694 includes both alphatrend and zigzag indicators, but as mentioned above, they are in two separate git commits.

No worries. Thanks for clarifying. I'll figure it out.

> But on the other hand, if possible, please merge the PRs as my team (and maybe some people who created or contributed in the issue) need these two indicators.

I will look into merging it after I merge PR #623 since it has been on hold for several months due to my _limited_ free time this past year. 😑

I appreciate your/team interest to contribute to this library. It really helps! 😎

KJ

**Comment by aligheshlaghi97** [comment]
@twopirllc You're very welcome, and thank you for your considerations despite your limited time.

And also I would like to say that I have more free times these days and so if you had any feedback, I would love to apply it into the code asap.

**Comment by KilianB** [comment]
@aligheshlaghi97 I attempted to use your code outside of pandas-ta but run into an error on a bigger time series. 

Reproducible example can be found here: https://colab.research.google.com/drive/1biUYxTmtgP0a76yBrdqbZuhKpmZy9tSV?usp=sharing#scrollTo=FkNAt_zoUCNM

Can you please help me understand if this is just an issue with my dataset or if there is a bug in your implementation?

**Comment by KilianB** [comment]
@aligheshlaghi97 sure, thanks for creating a python version of this useful indicator. The data I am using has been reconstructed from TickData downloaded from Dukascopy and in my case is reconstructed into 15 minute bars. If you take a look at the Colab notebook you should also have access to the data file. The link should be publicly accessible. 

My goal is to use the zigzag indicator as a pre filtering step to extract useful test data for further ml models, thus I am perfectly fine if it repaints and actually would prefer it to be identical to the version found inside the mt4 or mt5 instances.

I just rand your modified code and it is executing. Great :-), but there is still some unexpected behavior:  the arguments  `retrace` and `last_extreme` are unused in the code. 
The resulting zig zag somehow misses the extreme points:

````
range = 50000
deviation = 0.7
zz = zigzag(high = eur_usd['High'][:range],low = eur_usd['Low'][:range],price_deviation=deviation)
plt.plot(eur_usd['Close'][:range])
plt.plot(zz[1]["swing_value"])
````



image

Increasing the pivot leg value solves this misbehavior, but I don't quit understand what this value is for? 

image

**Comment by aligheshlaghi97** [comment]
@KilianB Thanks for your great job testing and utilizing this function. I totally understand that there might be some problems calculating this indicator, and thanks for sharing the pictures, but can you please clarify the parameters you passed resulting in these two pictures?

Also talking about retrace and last_extreme, I tried to use the definition of this indicator on [TradingView](https://www.tradingview.com/support/solutions/43000591664-zig-zag/#:~:text=Definition,trader%20visual%20the%20price%20action.), but I didn't know how to utilize those two variables. If you can help me how should I utilize them, it would be great.

And my suggestion is to see the MQL code for ZigZag indicator, so that we might have better insight over what is happening exactly regarding this indicator.

Best Regards,
Ali Gheshlaghi

**Comment by xukongwen** [comment]
hi, so is zigzag in pandas-ta now? i can't find it, what it's name? thanks!

**Comment by aligheshlaghi97** [comment]
Hi @xukongwen

> hi, so is zigzag in pandas-ta now? i can't find it, what it's name? thanks!

Yes it is. But you need to install development branch (instead of main) for now. Use this command:
`pip install -U git+https://github.com/twopirllc/pandas-ta.git@development`

After installation completed, you can import `zigzag` with this command in a python shell:
`from pandas_ta import zigzag`

**Pull request merged**
