### PR TITLE
Added lookahead interface to ichimoku and dpo indicators

### PR DESCRIPTION
**Pull request by bizso09**
Indicators with potential data leak should handle lookahead=False kwargs

### CODE REVIEW

**Comment by bizso09** [comment]
Another option I was considering is to add the `lookahead` to `strategy` method and then set the `include_chikou` and `centered` to `False` there, in case lookahead shouldn't be part of the individual indicators. 

However, I was thinking that `lookahead` can be supported the same way `fillna` and `fill_method` are supported in the interface of each indicator. Then invoking a strategy is very simple, and this ensures there's no data leak at the indicator level.

```
df.ta.strategy(ta.AllStrategy, lookahead=False)
```

**Comment by twopirllc** [comment]
Hey @bizso09,

Lets make the indicator changes first before touching ```df.ta.strategy```. See how it shakes out. Then we can pop in _lookahead_ into ```df.ta.strategy```. 😄 

KJ

**Comment by bizso09** [comment]
That's fine, let me know if you have a better idea on how to add this. The goal of this pull request is to provide a simple way in strategy to disable data leak, because that's a serious problem if you're doing backtesting. Right now, only two indicators have leak, as far as I'm aware.

**Comment by twopirllc** [comment]
@bizso09,

Currently, I do not have a better approach on this. I agree with you and I understand how data leaks can be a serious problem for AI/ML. Yes, there are only two indicators currently that lead. Go ahead and do what you consider appropriate and effective. I will merge it as soon a I can.

Thanks for your contributions. I appreciate it
KJ

**Pull request merged**
