### PR TITLE
TTM Squeeze PRO indicator #313

### PR DESCRIPTION
**Pull request by zlpatel**
Added a new indicator called squeeze_pro.
Added unit tests.

### CODE REVIEW

**Comment by twopirllc** [comment]
Hello @zlpatel,

This looks great! And you even provided tests! 😃 
I will try and roll this in soon!

Thank you for the contribution!
KJ

**Comment by twopirllc** [comment]
Hello @zlpatel,

It is up on the _development_ branch if you want to check it out before I push to _main_.
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Thanks,
KJ

**Comment by zlpatel** [comment]
@twopirllc I am unable to access squeeze_pro, when I download code from development branch.

Here's what I see when I install it:
```
Collecting git+https://github.com/twopirllc/pandas-ta
  Cloning https://github.com/twopirllc/pandas-ta to /tmp/pip-req-build-c_f_0r9l
  Running command git clone -q https://github.com/twopirllc/pandas-ta /tmp/pip-req-build-c_f_0r9l
Requirement already satisfied, skipping upgrade: pandas in /usr/local/lib/python3.7/dist-packages (from pandas-ta==0.2.93b0) (1.1.5)
Requirement already satisfied, skipping upgrade: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas->pandas-ta==0.2.93b0) (1.21.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pandas-ta==0.2.93b0) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas->pandas-ta==0.2.93b0) (2018.9)
Requirement already satisfied, skipping upgrade: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->pandas-ta==0.2.93b0) (1.15.0)
Building wheels for collected packages: pandas-ta
  Building wheel for pandas-ta (setup.py) ... done
  Created wheel for pandas-ta: filename=pandas_ta-0.2.93b0-cp37-none-any.whl size=207877 sha256=5d4a4e64936bc3ba1e0afc89d72bc5efe84936563582418818c15bc67a260f81
  Stored in directory: /tmp/pip-ephem-wheel-cache-9r5v8m6l/wheels/64/67/96/15e918c3b53b4a323b5bd037c7f08be5ef6908141c50f07c76
Successfully built pandas-ta
Installing collected packages: pandas-ta
  Found existing installation: pandas-ta 0.2.93b0
    Uninstalling pandas-ta-0.2.93b0:
      Successfully uninstalled pandas-ta-0.2.93b0
Successfully installed pandas-ta-0.2.93b0
```

why does it still reference `0.2.93b0` instead of `0.2.97b0` ?

Here's the error I get:

`module 'pandas_ta' has no attribute 'squeeze_pro'`

**Comment by zlpatel** [comment]
@twopirllc I figured it out. I needed to use below command to install package from development branch:

`!pip install -U git+https://github.com/twopirllc/pandas-ta.git@development`

**Comment by twopirllc** [comment]
@zlpatel,

 Doh! Sorry I sent the wrong link. Glad you found it.

**Comment by zlpatel** [comment]
@twopirllc I have tested it out in my code. It looks good.

**Pull request merged**
