### PR TITLE
Re-organized README and added a TOC

### PR DESCRIPTION
**Pull request by DrPaprikaa**
@twopirllc,

I took the initiative to re-organize a bit the README. I also added a table of contents to improve readability.

Let me know what you think,
DrPaprikaa

### CODE REVIEW

**Comment by twopirllc** [comment]
@DrPaprikaa,

Thanks!

I wonder if people will read more of the README that way before submitting an Issue?

KJ

**Comment by DrPaprikaa** [comment]
Since the README is quite long, I hope so ! It's easier that way, IMO, to find information.

Cheers,
DrParikaa

**Comment by DrPaprikaa** [comment]
Since the README is quite long, I hope so ! It's easier that way, IMO, to find information.

Cheers,
DrPaprikaa

**Comment by DrPaprikaa** [comment]
@twopirllc,

For reference, [tdqm](https://github.com/tqdm/tqdm) has a very clear & organized README, it can be an example for improvements to `pandas-ta`'s README. I hope this helps !

Cheers,
DrPaprikaa

**Comment by twopirllc** [comment]
Hi @DrPaprikaa,

There are definitely some good READMEs out there. Thanks for the reference, I'll check it out.

Thanks,
KJ

**Comment by DrPaprikaa** [comment]
Hi @twopirllc,

I see the new README in _development_, it's impressive ! Really nice :)

DrPaprikaa

**Comment by twopirllc** [comment]
@DrPaprikaa,

Thanks! Thanks for the suggestions. Also, I hope it is easy to understand and descriptive enough.

KJ

**Pull request merged**
