### PR TITLE
BUG #180 psar with dm init

### PR DESCRIPTION
**Pull request by AbyssAlora**
Parabolic Stop and Reverse (PSAR) construction did change as well as trend direction initialisation with Directional Movement (DM).

### CODE REVIEW

**Comment by twopirllc** [comment]
@AbyssAlora,

Will roll it in soon. I appreciate it. 😎 

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @AbyssAlora, @mtvu, and @AxelGUILLAUMET,

When you get a moment, please check out the _Development Version_ of **psar** before I update to the _Latest Version_. If you can not, no worries.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

I appreciate the help, feedback and contributions.

Thank you,
KJ

**Comment by AxelGUILLAUMET** [comment]
I just:

`pip install -U git+https://github.com/twopirllc/pandas-ta.git@development`

image

I get this error with the test script to excel I posted above... And all the rest of my experiments with pandas_ta

ModuleNotFoundError: No module named 'pandas_ta.utils.data'

Regards!

**Comment by twopirllc** [comment]
@AbyssAlora,

Doh! How about now?

Thanks,
KJ

**Comment by AbyssAlora** [comment]
Hi @twopirllc,
nice changes ;-) I wanted to change DM like this too, but you are faster :-D. I realized that there is one row I'm not sure about. 
```python
_sar = max(high.iloc[row - 1], high.iloc[row - 2], _sar) 
```
I think that second part of `max` this should not be there in the first iteration and similarly for falling trend. Had same problem as @AxelGUILLAUMET and now, there is a problem with DM calculation in psar because of index -1. 
```python
(((dn > up) & (dn > 0)) * dn).apply(zero)[-1] # Does not work
(((dn > up) & (dn > 0)) * dn).apply(zero).iloc[-1] # Works
```

With this change, looks, like psar works. 

AA

**Comment by AxelGUILLAUMET** [comment]
image

I call the PSAR like this:

`df_psar = ta.psar(df["high"],df["low"],df["close"])	`

**Comment by AbyssAlora** [comment]
@AxelGUILLAUMET yes that's it. This resolves that:
```python
(((dn > up) & (dn > 0)) * dn).apply(zero)[-1] # Does not work
(((dn > up) & (dn > 0)) * dn).apply(zero).iloc[-1] # Works
```

**Comment by twopirllc** [comment]
@AbyssAlora, @AxelGUILLAUMET,

Thanks for checking it out. So just
```python
(((dn > up) & (dn > 0)) * dn).apply(zero).iloc[-1] # Works
```
will do?

Thanks,
KJ

**Comment by AbyssAlora** [comment]
@twopirllc worked for me 🙂

AA

**Comment by AxelGUILLAUMET** [comment]
OK I just tested with the par that gives a difference with Binance, this one I relate there:

[](https://github.com/twopirllc/pandas-ta/issues/180)

With this new version, I have the same "false" entry on LTO/USDT 5 MIN at 16:15 07/JUN/2021 in UTC TIME.

I join there the CSV

[out.xlsx](https://github.com/twopirllc/pandas-ta/files/6679581/out.xlsx)

Regards.

**Comment by twopirllc** [comment]
@AxelGUILLAUMET,

With the above fix: ```(((dn > up) & (dn > 0)) * dn).apply(zero).iloc[-1]```, I am not sure what more can be done to minimize the differences.

## Results

### **Source** 

From TV: [BF_LTOUSDT_5m.csv](https://github.com/twopirllc/pandas-ta/files/6681146/BF_LTOUSDT_5m.csv)

### **Comparison Code**

```python
def background_gradient(s, m, M, cmap="Blues", low=0, high=0):
    rng = M - m
    norm = colors.Normalize(m - (rng * low), M + (rng * high))
    normed = norm(s.values)
    c = [colors.rgb2hex(x) for x in plt.cm.get_cmap(cmap)(normed)]
    return ["background-color: %s" % color for color in c]

def psar_diff(path, **kwargs):
    df = pd.read_csv(path)
    df.set_index(pd.DatetimeIndex(df["time"]), inplace=True, drop=True)
    df.drop("time", axis=1, errors="ignore", inplace=True)

    # TV P/SAR
    df.rename(columns={"ParabolicSAR": "TV_PSAR"}, errors="ignore", inplace=True) # "TV_PSAR_0.02_0.02_0.2"
    # TA Lib
    df["TAL_PSAR"] = tal.SAR(df["high"], df["low"]).fillna(0) # Uses Wilder 2 decimal rounding
    # PTA
    psar = df.ta.psar()
    psar = psar[psar.columns[:2]].fillna(0)
    psar = psar[psar.columns[0]] + psar[psar.columns[1]]
    psar.name = "PTA_PSAR"
    df[psar.name] = psar

    df.drop(kwargs.pop("dropcols"), axis=1, errors="ignore", inplace=True)

    if kwargs.pop("total_corr", True):
        # Assumes last 3 columns are PSAR
        print(f"Total Correlation from: {df.index[0]} to {df.index[-1]} [{df.shape[0]} bars]\n{df[df.columns[-3:]].corr()}\n")

    n = kwargs.pop("n", 0)
    if n > 0: df = df[:n]
    elif n < 0: df = df[n:]

    a, b = kwargs.pop("t0", None), kwargs.pop("t1", None)
    if isinstance(a, str) and isinstance(b, str):
        df = df.loc[a:b]
    
    if kwargs.pop("range_corr", True):
        # Assumes last 3 columns are PSAR
        print(f"Range Correlation from: {df.index[0]} to {df.index[-1]} [{df.shape[0]} bars]\n{df[df.columns[-3:]].corr()}\n")
    
    return df

# Adjust settings as needed
kw = {"dropcols": ["open", "high", "low", "volume", "VMA", "dividends", "stock splits"]}
kw.update({"n": -3000}) # Last n bars
kw.update({"t0": "2021-06-07 16:00", "t1": "2021-06-07 16:55"}) # That hour
# kw.update({"t0": "2021-06-07 15:00", "t1": "2021-06-07 17:55"}) # Hours: 15 - 17
# kw.update({"t0": "2021-06-07", "t1": "2021-06-07"}) # That day
df = psar_diff("BF_LTOUSDT_5m.csv", **kw)

df.plot(figsize=(16, 5), color=["black", "blue", "purple", "red", "orange"], title="PSAR diff", grid=True)
df.style.apply(background_gradient, cmap="bwr", m=df.min().min(), M=df.max().max(), low=1, high=0.5)
```

### **Output**
Screen Shot 2021-06-19 at 11 15 35 AM
Screen Shot 2021-06-19 at 11 15 43 AM

<br/>

Again [TV SAR](https://www.tradingview.com/pine-script-reference/v4/#fun_sar) provides **no** insight on which series it uses while TA Lib uses only ```high``` and ```low```. Furthermore any additional contributions to for **psar** are open, just make a new _PR_.

Kind Regards,
KJ

**Comment by AbyssAlora** [comment]
@AxelGUILLAUMET,
@twopirllc is right and in addition, Binance has different construction of PSAR in compare to TV. As I mentioned in #180 I have similar version to Binance as well, but there is no way that both of them will work (without version selection of course).

Best regards,
AA

**Pull request merged**
