### PR TITLE
Update adx to include lensig

### PR DESCRIPTION
**Pull request by JoeSchr**
There should be a additional parameter so ADX smoothing and DI Length can have different values. I compared it to TradingViews DMI calculation and they also offer this.
Thanks for this great lib!

### CODE REVIEW

**Review by twopirllc — APPROVED** [review]
Looks good!

**Comment by twopirllc** [comment]
Hello @JoeSchr,

> There should be a additional parameter so ADX smoothing and DI Length can have different values. I compared it to TradingViews DMI calculation and they also offer this.

Excellent! I will roll it in as soon as I can.

> Thanks for this great lib!

Thank you!
KJ

**Comment by JoeSchr** [comment]
I missed the format uses of length for ADX so I updated this as well

**Comment by twopirllc** [comment]
@JoeSchr,

Thanks for contributing and adding that argument. It's been merged into _development_ version. 
If you would like to test it out before it gets pushed to _main_, you can install the _development_ version:

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

I hope to push it to _main_ no later than this weekend.

Thanks,
KJ

**Pull request merged**
