### PR TITLE
ha 100x faster using numpy/numba

### PR DESCRIPTION
**Pull request by wassname**
Feel free to use or reject, I just wanted to offer my own code to give back and help. 

I got frustrated that the HA candles took longer than anything else, so I removed the pandas operations that were slowing it down. This is 100x faster and gives the same result to within 4 decimal places.

### CODE REVIEW

**Comment by wassname** [comment]
The candle tests pass (I assume the other ones are broken on dev, or I'm missing a dependancy): 

image

**Comment by wassname** [comment]
Benchmark

image

**Comment by twopirllc** [comment]
Hi @wassname,

Fantastic! Will merge it in ASAP.

Looking for more help converting more indicators to _numpy/jit_, so I appreciate it. 😎

Thanks
KJ

**Comment by wassname** [comment]
Great!

It's two years of tesla (of course ;p) 5min data, so 98486 rows.

**Pull request merged**
