### PR TITLE
ATR MA update in line with TradingView

### PR DESCRIPTION
**Pull request by YuvalWein**
The function always calculated ATR in EMA mode.
Changed code and documentation a little bit, to fix it.

### CODE REVIEW

**Comment by YuvalWein** [comment]
I noticed that I forgot to add the: 
`from pandas_ta.overlap import ema, rma, sma
` 
At the top, needs to be added.

**Review by twopirllc — CHANGES_REQUESTED** [review]
Well TradingView is using RMA as default now:
```
//@version=4
study(title="Average True Range", shorttitle="ATR", overlay=false, resolution="")
length = input(title="Length", defval=14, minval=1)
smoothing = input(title="Smoothing", defval="RMA", options=["RMA", "SMA", "EMA", "WMA"])
ma_function(source, length) =>
	if smoothing == "RMA"
		rma(source, length)
	else
		if smoothing == "SMA"
			sma(source, length)
		else
			if smoothing == "EMA"
				ema(source, length)
			else
				wma(source, length)
plot(ma_function(tr(true), length), title = "ATR", color=#991515, transp=0)
```

So it would be great if you fixed it up like TradingView please.

Thanks,
KJ

**Comment by YuvalWein** [comment]
Ok, no problem,
I will fix it soon.

**Review by twopirllc — APPROVED** [review]
Thanks Yuval!

**Pull request merged**
