### PR TITLE
Add GHA workflow for testing to the development branch

### PR DESCRIPTION
**Pull request by Karsten-Fyhn**
This is a mirror PR of #582 but against the development branch.

### CODE REVIEW

**Comment by twopirllc** [comment]
@Karsten-Fyhn,

Almost there! 😎 

Can you include installing module: ```pandas_datareader``` in the GHA?

Thanks,
KJ

**Comment by Karsten-Fyhn** [comment]
@twopirllc closer, but no cigar :) It seems like now there is some missing directory, `csv` - is there some code that should have autogenerated that directory, but didn't?

**Comment by twopirllc** [comment]
@Karsten-Fyhn

Yeah closer 😎 

No csv/ is an excluded directory in .gitignore. In the process of fixing on my end...

**Comment by twopirllc** [comment]
@Karsten-Fyhn,

Almost there it seems. I really appreciate the help.

So it is installing _v0.3.71b_, but it needs the latest _development_ branch is _v0.3.73b_ (which is using a new SPY_D.csv from data/ and not csv/).

Any ideas?

Thanks

**Comment by Karsten-Fyhn** [comment]
Excellent - glad to get it in. Thanks for all your help finalizing it! What is your thoughts on the failing tests? Are they easy to fix? Or are they irrelevant and perhaps the tests should be removed?

**Comment by twopirllc** [comment]
@Karsten-Fyhn,

No, thank you for your patience and commitment to help me get a GHA up and running. Seems they are failing because they are not pytest compliant. I got it working with the current ```python -m unittest -v -f tests/<tests>.py``` commands. I am confident the pytest command will work when I migrate the tests to pytest style.

Thanks again for all your help. 😎 
KJ

**Comment by Karsten-Fyhn** [comment]
@twopirllc: Even with the changes you made to uses unittest instead of pytest, I am still struggling with failing tests :( I have made this draft PR: #601 to exemplify. Both in the pipeline and locally, I keep failing on this test: test_custom_a_with_multiprocessing (tests.test_study.TestStudyMethods) - is this a test I can easily fix somehow? Or should it be skipped instead?

**Pull request merged**
